### ISSUE TITLE
Enable code to store media locally with a flag variable in the .env file

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/sharechat-scraper#1]
I propose adding a variabled called MODE in the .env file. when its set to the value 'local' or 'debug', it should scrape media and metadata from sharechat and store the images and metadata locally on disk instead of saving it on mongo or s3.

**Comment by kruttikanadig** [comment]
Mode selection is now enabled in `config.py`. When mode is set to "local" the scraped content will only be saved locally as csv and html files. When it is set to "archive" the content will additionally be stored on Mongo and S3.
