### ISSUE TITLE
Configure cron job to scrape data for permanent tags

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/sharechat-scraper#7]
@kruttikanadig As @whymath is working on creating a cron job to do this, we'd want the command that the cron job can run to start the scraper. could you help us finalize that?

**Comment by dennyabrain** [comment]
I think we run `python run config.py` and as long as the right values are in the configuration file, we should be able to trigger the scraper?

if thats correct could you document here, what values need to be in the config.py file?

**Comment by kruttikanadig** [comment]
Yes, `python run config.py` will start the scraper.
`config.py` contains a dictionary named scraper_params whose values need to be modified before scraping.
scraper_params takes the following key:value pairs -

**"USER_ID":** os.environ.get("SHARECHAT_USER_ID")
**"PASSCODE":** os.environ.get("SHARECHAT_PASSCODE")
User id and passcode should be saved in the .env file.
**"tag_hashes":** <tag_hashes_passed_as_list_of_strings>
Tag hashes are identifiers for content tags. I'll share tags for the permanent tags cron job shortly (the list of tags would be different for different languages and scrapers)
**"content_to_scrape":** <string_value>
This value determines which scraper will be launched by the scraper manager. Current possible values are "trending", "fresh", "ml" and "virality"
**"pages":** <integer_value>
Number of pages to scrape. One page typically contains 10 posts. This is a required value when **"content_to_scrape":** "trending" or "fresh" or "ml". This number should be kept reasonably low to avoid bombarding the Sharechat API with requests.
**"unix_timestamp":** <10_digit_unix_timestamp_passed_as_string>
This is a required value when content_to_scrape="fresh", and it determines the point from which the scraper will start scraping backwards in time
**"data_path":** Path to a local CSV file containing previously scraped Sharechat content. Currently, this is a required value when content_to_scrape="virality". The virality scraper (in development stage) will scrape and update the current virality metrics for the Sharechat posts in this file. In future, virality metrics will be updated directly in the Sharechat Mongo DB and this key will be removed from scraper_params.

**Comment by dennyabrain** [comment]
thanks! great. once you have the tag hashes, can you paste it here and maybe also just paste the entire config.py with real values (just to be sure). I'll hand that off to yohan at that point. thank you

**Comment by dennyabrain** [comment]
@tarunima this is slightly related but would you happen to have the cron job definition for your whatsapp scraper somewhere?

**Comment by kruttikanadig** [comment]
Update: Mode selection is now enabled in `config.py`. I've updated my comment describing `config.py` above.

**Comment by whymath** [comment]
Thanks @kruttikanadig; I'll test this out over the next week and get back to you if I need any more info

@tarunima, in case you're able to find the cron job definition for the Whatsapp scraper, that would help as well

**Comment by dennyabrain** [comment]
I wanted to start defining acceptance criteria for this task
1. the obvious one : some kind of cron job needs to be configured that triggers the task of scraping once a day
2. ensuring that the cron job is triggered with the right frequency once setup (@whymath responsible). As @kruttikanadig monitors our database and notices that new data wasn't added for that day, she will first ping yohan to check if the cron job was triggered or not. So at the least there should be a quick way to check history of cron job triggers
3. If the cron job ran, we have two possibilities
    1. everything worked as expected (nothing needs to be done)
    2. something went wrong : kruttika will need to inspect logs -> debug with the help of yohan -> re trigger the job for the day -> redeploy with the changes

I foresee 3.ii becoming a timesink, so hopefully we can put some processes in place to make this workflow smooth.

this is due on 26/06/20, we can redefine/tweak some of the criteria. let me know!

**Comment by kruttikanadig** [comment]
@whymath I've added a key called `is_cron_job` to `config.py` which takes boolean values.  Setting it to True will automatically generate the current UNIX timestamp (required by the fresh content scraper) when the cron job is triggered. This will override any UNIX timestamp that is manually entered in `config.py`. 
@dennyabrain any other distinctions we want to create between cron jobs and manual scraping could also be enabled via the `is_cron_job` key.

**Comment by dennyabrain** [comment]
yes sounds good. it also takes care of 3.ii 
if there's a bug, you could run the scraper with is_cron_job = false till you resolve the issue and then redeploy the scraper with is_cron_job=true.

**Comment by tarunima** [comment]
@whymath does this work? https://github.com/tattle-made/whatsapp-public-group-discoverer

**Comment by dennyabrain** [comment]
@tarunima yohan was curios to look at the cronjob configuration itself.
i think you wrote it in a crontab file (i might be wrong)

**Comment by tarunima** [comment]
Got it. 
executed this script via crontab: https://github.com/tattle-made/whatsapp-public-group-discoverer/blob/master/runWglScraper.sh

**Comment by tarunima** [comment]
If its really worth looking for the crontab command, I can dig it up. But it will take me some time.  If an approximation works, this is what it was like:
0 23 * * * /path_to_dir/runWglScraper.sh
A cron job to run at 11pm every day.

**Comment by dennyabrain** [comment]
this is good enough for now.

**Comment by kruttikanadig** [comment]
@whymath here are the two scraper_params configurations for the trending and fresh content cron jobs, respectively. You can copy paste them into `config.py` and run the file. 

**For the trending content cron job -**

```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": ['5anPZA', 'Kyweq', 'njWVe', '6aj68', 'e5jM8'],
    "content_to_scrape": "trending",
    "pages": 1,
    "unix_timestamp": "",
    "data_path": "", 
    "mode": "archive", 
    "is_cron_job": True
    }
```

**For the fresh content cron job -**

```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": ['5anPZA', '3NE91Z', 'xprBMR', 'EXrjQQ', 'Kyweq', 'Wm3D1', '0eXrv', '7dqOZn', 'rlreB', 'PP3r5z', 'VVlpO', 'ZXE81', 'DkXeO', 'ekz6a8', 'WBe5J', 'AAjO5', 'ZwRVR', 'OaaXqJ', 'bvwgmD', 'jR00yv', 'ZQbgkR', 'X6vKRZ', '5anxp4', '7daJbA', 'B0JNwR', 'ekz6ag', 'OaEgB', 'Pewzz', 'wVkEw', '3675j', 'ENM', 'r19V5', 'kAjE3', 'vJmqk', 'Ey0Ge', 'll7a88', '7dqR6k', 'pk7893', 'Dy4Vd8', 'GEpDm3', '8rqVej', 'RPJdBK', 'MXegrk', 'pAgnK', 'Bb4ek', 'Ew98N', 'DyjQK', 'WOWM6', 'njWVe', 'kdrMq', 'lleDJW', '6aj68', 'aKgp9', 'e5jM8', 'jg779', 'RAKJy', '6e4', 'B0QGO', 'AD6WZ', 'G7Pa0', '1Rb7R'],
    "content_to_scrape": "fresh",
    "pages": 5,
    "unix_timestamp": "",
    "data_path": "", 
    "mode": "archive", 
    "is_cron_job": True
    }
```

Note: some of the cron job tags are semi-permanent (topics that are expected to be in the news for a while) so we'll be revisiting the tag hash lists every 30 days or so to delete / add tags as needed.

**Comment by kruttikanadig** [comment]
@dennyabrain It just occurs to me that we could tweak Config to accept bucket ids instead of tag hashes, so that the cron job scrapes all tags (permanent and transient) available within targeted buckets every day. The existing scrapers don't employ this approach because it offers less flexibility during manual scraping.
@whymath do you think this change can be made easily if I create a branch called cron_job with the modified Config and scraper files? I'll just have to write a helper function that pings the Sharechat API for the list of tags within a particular bucket. This function can return tag hashes, so the rest of the workflow would be the same.

**Comment by kruttikanadig** [comment]
Post a verbal discussion about this with Denny and Tarunima, I've tweaked Config and the other scraper files to allow bucket scraping while retaining the more flexible but involved option of scraping specific tags only. 

@whymath sorry about all this back and forth! The revised scraper_params configurations for `config.py` are -

For the trending content cron job -

```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": ["5anPZA", "Kyweq", "njWVe", "6aj68", "e5jM8"],
    "bucket_ids": [],
    "content_to_scrape": "trending",
    "pages": 1,
    "unix_timestamp": "",
    "data_path": "", 
    "mode": "archive", 
    "targeting": "tag",
    "is_cron_job": True
    }
```
For the fresh content cron job -

```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": [],
    "bucket_ids": ["125", "1284", "371", "1075"],
    "content_to_scrape": "fresh",
    "pages": 5,
    "unix_timestamp": "",
    "data_path": "", 
    "mode": "archive", 
    "targeting": "bucket",
    "is_cron_job": True
    }

```

**Comment by kruttikanadig** [comment]
### How to trigger the scrapers

```
python3 config_fresh_cron.py 
python3 config_trending_cron.py 
```

Note: the scrapers should be triggered at different times of the day since they both use the same Sharechat user credentials.

### How to know if they're working

**Output (in local & archive mode)**

Both scrapers should output one CSV and one HTML file to disk. The following statements will be printed when the job is complete:

```
HTML preview file created
CSV file created
```

**Scraped data count (in local & archive mode)**

The scrapers will print the following when the job is complete, telling you if any posts were scraped:

```
<n> posts scraped
Scraping complete
```

**Upload confirmations (in archive mode)**

The scrapers should print the following statements in the same order, confirming that data has been uploaded properly:

```
Data uploaded to S3 
Data uploaded to MongoDB
```

**Time taken**

config_fresh_cron.py  should typically take ~4 hrs and config_trending_cron.py ~30 minutes to complete.

**Comment by kruttikanadig** [comment]
@whymath Thanks for the smooth cron job deployment. We'd like to increase the trending scraper's reach by changing its targeting from tag to bucket. Here is the updated config for the trending cron job. Estimated runtime for this is ~3 hrs. 

```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": [],
    "bucket_ids": ["125", "1284", "371", "1075", "1274", "515", "1244", "1281", "648", "127"],
    "content_to_scrape": "trending",
    "pages": 2,
    "unix_timestamp": "",
    "data_path": "", 
    "mode": "archive", 
    "targeting": "bucket",
    "is_cron_job": True
    }
```

**Comment by whymath** [comment]
@kruttikanadig The SC API handling fix and the cron job config updated were both successfully updated and tested, thanks!

**Comment by whymath** [comment]
Hey everyone sharechat scraper has now been deployed as a cron job on our Kubernetes dev cluster, and the monitoring of the logs and the servers has been setup as well.

Thank you @kruttikanadig for all the help and the detailed inputs, and thanks @tarunima and @dennyabrain for your help!
