### ISSUE TITLE
Fix media-type error

### ISSUE THREAD

**Issue by kruttikanadig** [tattle-made/sharechat-scraper#8]
Sharechat's platform-generated metadata includes the media type of each post. Our scraper scrapes this field but sometimes when the media type is "text", we find the post is actually an embedded link or something else. This becomes a problem when we're sorting or annotating the dataset. Can someone come up with a fix so that the scraper checks every post with the "text" media type and updates the field if needed? 
Example - in the attached screenshot, the field "t" in the response preview says the media type is text, when the post is actually a link to another post.

![Screenshot 2020-08-06 at 11 18 21 (2)](https://user-images.githubusercontent.com/56830089/89496733-899e9280-d7d8-11ea-848f-33fce0ae0b68.png)

**Comment by duggalsu** [comment]
Hi @kruttikanadig , I would like to work on this issue. Could you assign this task to me?

**Comment by kruttikanadig** [comment]
Thanks for taking this up @duggalsu . Let me know if you need more information!

**Comment by duggalsu** [comment]
The mentioned post (text post type) is a "repost" of the original (link post type). 

I have the following queries -

1. I cannot seem to find any way to repost / view number of reposts on sharechat in the web UI. I can't seem to find any info via search/website either except that they had added repost functionality. Have they removed this feature?

2. Are you archiving reposts separately? If so, should they be categorized separately (not as image/video/text) as they will possibly always be of type text with different types of repost data.

**Comment by kruttikanadig** [comment]
Hi @duggalsu -

1. You're right that reposting doesn't seem to be an option in the web UI, but it is an option on the Sharechat mobile app.

2. No, we're not archiving them separately as of now. And yes we would want to assign them a new media type called 'repost' instead of image/video/text, but that would be dependent on the scraper being able to identify them correctly in the first place. 

3. Not that we know of.

**Comment by duggalsu** [comment]
I can correctly detect reposts. 

How shall I handle saving these posts? Shall I open another issue for that? Currently, I can assign the "repost" label but there is no way to handle how it is saved. 

Options
1. Save the original post with the link to the shared post as text 
2. Traverse to the shared post and save its content (image/video/text) and append this link to the original post's text
3. Other options?

**Comment by kruttikanadig** [comment]
Great! 

`sharechat_helper.py ` contains the helper functions that send API requests, scrape the post metadata fields, store them temporarily in a dataframe and then upload them to Mongo DB in each run of the scraper. You should also be able to run the scraper locally with `mode:local` which saves everything as a CSV - please let me know if that doesn't work.

It sounds like option 1 would be ideal, assuming that 'original post' refers to the Prabhat Khabar post in the example above. Would this option involve additional API requests? I'm not sure how to read option 2 - we are already at the 'shared' post (chhotu raj's post in the example) and there is no content to save.

Let me know what you think is feasible!

**Comment by duggalsu** [comment]
Just to clarify how I thought about the options -

- Original post by: chotu Raj
- shared post by: Prabhat Khabar

Option 1 - Save the original post with the link to the shared post as text
Save as -
- post by: chotu Raj
- type: repost
- content: "<text from chotu Raj>, Repost: <link to post by Prabhat Khabar>"

Now that I think over it, option 2 above does not make sense.

I read your option on saving as - 
Save as -
- post by: Prabhat Khabar
- type: repost
- content: 
    - <content from Prabhat Khabar>
    - text: <link to post by chotu Raj>

What do you recommend I do?

**Comment by kruttikanadig** [comment]
Let's go with option 1 as you have described for now, since (as I understand) that will save the link to the shared post without extra API requests.

**Comment by kruttikanadig** [comment]
Let's go with option 1 since (as I understand) that will save the link to the shared post without any extra API requests.

**Comment by duggalsu** [comment]
Sure!

**Comment by kruttikanadig** [comment]
I've verified that the fix is working properly (scraping and saving reposts to the database in the format we discussed). Closing this issue. Thanks for your help @duggalsu !
