### ISSUE TITLE
Deploy virality scraper

### ISSUE THREAD

**Issue by kruttikanadig** [tattle-made/sharechat-scraper#9]
Hello @whymath  ,

The virality scraper is ready for deployment. As discussed, we'll split this into two parallel cron jobs to reduce runtime. I suggest we start by running them at 12 pm daily. (We'll review the results and see if the time needs to be changed later)

To run the jobs, `config.py` needs to be triggered with the following scraper parameters - 

**Job 1**
```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": ["", ""], 
    "bucket_ids":["", ""],
    "content_to_scrape": "virality", 
    "pages": "", 
    "unix_timestamp": "", 
    "virality_job": 1, 
    "mode": "archive", 
    "targeting": "", 
    "is_cron_job": True
    }
```

**Job 2**
```
scraper_params = {
    "USER_ID": os.environ.get("SHARECHAT_USER_ID"),
    "PASSCODE": os.environ.get("SHARECHAT_PASSWORD"), 
    "tag_hashes": ["", ""], 
    "bucket_ids":["", ""],
    "content_to_scrape": "virality", 
    "pages": "", 
    "unix_timestamp": "", 
    "virality_job": 2, 
    "mode": "archive", 
    "targeting": "", 
    "is_cron_job": True
    }
```

I'll share Sharechat credentials for these jobs separately. Note that the old parameter `data_path` is replaced with a new parameter called `virality_job`. This shouldn't affect anything but please let me know in case it does.

**Comment by whymath** [comment]
Hey @kruttikanadig deployment of the 2 virality scrapers was done last week and was monitored this week. They've been running successfully on the production cluster now. Monitoring for them has been setup as well.

Closing this issue.
